# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '414ddffa-6500-4311-a4de-36edccee121c'
  imageRepository: 'rapimpackagetools'
  containerRegistry: 'apimemt.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'
  
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: UniversalPackages@0
      inputs:
        command: 'download'
        downloadDirectory: '$(System.DefaultWorkingDirectory)'
        feedsToUse: 'internal'
        vstsFeed: '878c65e7-0897-4085-87c3-357a72b45fb1/31e859cf-4f29-490c-9e3f-556992b09855'
        vstsFeedPackage: 'c5178fbc-376a-433d-b3a1-1cdae1947222'
        vstsPackageVersion: '7.7.20200330'
    - task: Docker@2
      inputs:
        containerRegistry: $(dockerRegistryServiceConnection)
        command: 'build'
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        arguments: '--build-arg $(System.DefaultWorkingDirectory)'
    